### ISSUE TITLE
Summons a default mount when in a sub zone without region text (i.e. Isle of Dorn in Isle of Dorn)

### ISSUE THREAD

**Issue by socalpoet29** [trozware/ZoneMount#3]
If you are in a section of a zone where there is no world map region text (i.e. the region text is the same as zone name; e.g. 51.37, 40.72 Hallowfall or 50.63, 71.24 Isle of Dorn), then a default mount is summoned instead of a zone specific mount. 

I fixed the issue by doing an additional check on subZone string length and will raise a pull request shortly.

Thanks!

**Comment by trozware** [comment]
This is all merged in now, along with some other fixes. Thanks for the reports and PRs.
